apiVersion: v1
kind: Service
metadata:
  name: trainee-service-dev
  namespace: dev
spec:
  selector:
    app: trainee
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30001
  type: NodePort
