apiVersion: v1
kind: Service
metadata:
  name: trainee-service-prod
  namespace: prod
spec:
  selector:
    app: trainee
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30003
  type: NodePort
